server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: code-visualizer
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

# Enable detailed logging for development
logging:
  level:
    com.codevisualizer: DEBUG
    org.springframework.web: INFO