package lexer;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 11;
  public static final int MOD = 13;
  public static final int AND = 19;
  public static final int SEMICOLON = 28;
  public static final int ELSE = 4;
  public static final int PLUS = 9;
  public static final int RBRACE = 27;
  public static final int RPAREN = 25;
  public static final int OR = 18;
  public static final int DECREMENT = 15;
  public static final int IDENTIFIER = 32;
  public static final int RETURN = 6;
  public static final int INPUT_INT = 30;
  public static final int GREATER = 23;
  public static final int FUNCTION = 2;
  public static final int TRUE = 7;
  public static final int IF = 3;
  public static final int LBRACE = 26;
  public static final int LPAREN = 24;
  public static final int LESSEQUAL = 20;
  public static final int EQUALS = 17;
  public static final int COMMA = 29;
  public static final int EOF = 0;
  public static final int DIVIDE = 12;
  public static final int INCREMENT = 14;
  public static final int FALSE = 8;
  public static final int MINUS = 10;
  public static final int error = 1;
  public static final int ASSIGN = 16;
  public static final int INTEGER_LITERAL = 33;
  public static final int FOR = 5;
  public static final int OUTPUT_INT = 31;
  public static final int GREATEREQUAL = 21;
  public static final int LESS = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FUNCTION",
  "IF",
  "ELSE",
  "FOR",
  "RETURN",
  "TRUE",
  "FALSE",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MOD",
  "INCREMENT",
  "DECREMENT",
  "ASSIGN",
  "EQUALS",
  "OR",
  "AND",
  "LESSEQUAL",
  "GREATEREQUAL",
  "LESS",
  "GREATER",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "SEMICOLON",
  "COMMA",
  "INPUT_INT",
  "OUTPUT_INT",
  "IDENTIFIER",
  "INTEGER_LITERAL"
  };
}

